### ISSUE TITLE
AttributeError: 'Trainer' object has no attribute 'log_dir'

### ISSUE THREAD

**Issue by mingu0807** [lojzezust/WaSR#1]
Would you please let me know why the following error occur?

Best Regards
```
AttributeError: 'Trainer' object has no attribute 'log_dir'
```

```
(WASR) wkyoun@wkyoun-Bonobo-WS:~/다운로드/WaSR-masters$ python train.py --train_config configs/mastr1325_train.yaml --val_config configs/mastr1325_val.yaml --model_name my_wasr --validation --batch_size 2 --epochs 1
Namespace(batch_size=2, epochs=1, focal_loss_scale='labels', gpus=-1, learning_rate=1e-06, log_steps=20, lr_decay_pow=0.9, model='wasr_resnet101_imu', model_name='my_wasr', momentum=0.9, monitor_metric='val/iou/obstacle', monitor_metric_mode='max', no_augmentation=False, no_separation_loss=False, num_classes=3, output_dir='output', patience=None, precision=32, pretrained=True, pretrained_weights=None, random_seed=None, resume_from=None, separation_loss_lambda=0.01, train_config='configs/mastr1325_train.yaml', val_config='configs/mastr1325_val.yaml', validation=True, weight_decay=1e-06, workers=1)
No correct seed found, seed set to 3989317893
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    main()
  File "train.py", line 155, in main
    train_wasr(args)
  File "train.py", line 143, in train_wasr
    precision=args.precision, log_dir="./log_dir")
  File "/home/wkyoun/anaconda3/envs/WASR/lib/python3.6/site-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 41, in overwrite_by_env_vars
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'log_dir'
(WASR) wkyoun@wkyoun-Bonobo-WS:~/다운로드/WaSR-masters$ python train.py --train_config configs/mastr1325_train.yaml --val_config configs/mastr1325_val.yaml --model_name my_wasr --validation --batch_size 2 --epochs 1
Namespace(batch_size=2, epochs=1, focal_loss_scale='labels', gpus=-1, learning_rate=1e-06, log_steps=20, lr_decay_pow=0.9, model='wasr_resnet101_imu', model_name='my_wasr', momentum=0.9, monitor_metric='val/iou/obstacle', monitor_metric_mode='max', no_augmentation=False, no_separation_loss=False, num_classes=3, output_dir='output', patience=None, precision=32, pretrained=True, pretrained_weights=None, random_seed=None, resume_from=None, separation_loss_lambda=0.01, train_config='configs/mastr1325_train.yaml', val_config='configs/mastr1325_val.yaml', validation=True, weight_decay=1e-06, workers=1)
No correct seed found, seed set to 2179451097
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/1

  | Name         | Type          | Params
-----------------------------------------------
0 | model        | WaSR          | 84 M  
1 | val_accuracy | PixelAccuracy | 0     
2 | val_iou_0    | ClassIoU      | 0     
3 | val_iou_1    | ClassIoU      | 0     
4 | val_iou_2    | ClassIoU      | 0     
INFO:lightning:
  | Name         | Type          | Params
-----------------------------------------------
0 | model        | WaSR          | 84 M  
1 | val_accuracy | PixelAccuracy | 0     
2 | val_iou_0    | ClassIoU      | 0     
3 | val_iou_1    | ClassIoU      | 0     
4 | val_iou_2    | ClassIoU      | 0     
/home/wkyoun/anaconda3/envs/WASR/lib/python3.6/site-packages/pytorch_lightning/utilities/distributed.py:45: UserWarning: The dataloader, val dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)
Validation sanity check: 0it [00:00, ?it/s]/home/wkyoun/anaconda3/envs/WASR/lib/python3.6/site-packages/torchvision/transforms/functional.py:365: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "
/home/wkyoun/anaconda3/envs/WASR/lib/python3.6/site-packages/pytorch_lightning/utilities/distributed.py:45: UserWarning: The dataloader, train dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)
Epoch 0:   0%|                                           | 0/37 [00:00<?, ?it/s][W reducer.cpp:1050] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters. This flag results in an extra traversal of the autograd graph every iteration, which can adversely affect performance. If your model indeed never has any unused parameters, consider turning this flag off. Note that this warning may be a false positive your model has flow control causing later iterations to have unused parameters. (function operator())
Epoch 0: 100%|████████████| 37/37 [00:46<00:00,  1.27s/it, loss=0.166, v_num=55Saving latest checkpoint...                                                      
INFO:lightning:Saving latest checkpoint...
Epoch 0: 100%|████████████| 37/37 [00:46<00:00,  1.27s/it, loss=0.166, v_num=55]
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    main()
  File "train.py", line 155, in main
    train_wasr(args)
  File "train.py", line 148, in train_wasr
    trainer.fit(model, train_dl, val_dl) #, log_dir)
  File "/home/wkyoun/anaconda3/envs/WASR/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 451, in fit
    self.call_hook('on_fit_end')
  File "/home/wkyoun/anaconda3/envs/WASR/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 833, in call_hook
    trainer_hook(*args, **kwargs)
  File "/home/wkyoun/anaconda3/envs/WASR/lib/python3.6/site-packages/pytorch_lightning/trainer/callback_hook.py", line 57, in on_fit_end
    callback.on_fit_end(self, self.get_model())
  File "/home/wkyoun/다운로드/WaSR-masters/wasr/utils.py", line 23, in on_fit_end
    export_path = os.path.join(trainer.log_dir, 'weights.pth')
AttributeError: 'Trainer' object has no attribute 'log_dir'

```

**Comment by lojzezust** [comment]
The error seems pytorch-lightning related. Which version of pytorch-lightning are you using?

Also, you seem to have altered the training code (train.py) somewhat.  The following is not present in the original script:

```
  File "train.py", line 143, in train_wasr
    precision=args.precision, log_dir="./log_dir")
```

**Comment by lojzezust** [comment]
Closed due to inactivity.
